appid='oop_1725122496904'
env='dev'
net='http' #http or ws

port=3000
auth=true #关闭登录拦截
secret='mlkJHY9MTkkbT02NTUz'  #登录，和登录拦截jwt密钥
blacklist=["/user/login",'/user/captcha',"/system/get"]  #接口白名单,未登录不拦截

[pg]
dsn='postgres://postgres:root@localhost:5432/odb'
