appid='oop_1725122496904'
env='dev'
net='http'
port=3000
secret='mlkJHY9MTkkbT02NTUz'
auth=true
blacklist=["/user/login",'/user/captcha',"/system/get"]
[pg]
dsn='postgres://postgres:root@localhost:5432/odb'
